### PR TITLE
Line up alias command names

### PR DESCRIPTION
**Pull request by digitalsadhu**
This lines up command and class naming with the servers namespace types `map`, `npm` and `pkg`.

Commands are now:

For `/pkg/`
```sh
eik package # eik pkg also works
eik package-alias # eik pkg-alias also works
```

For `/map/`
```sh
eik map
eik map-alias 
```

For `/npm/`
```sh
eik npm
eik npm-alias 
```

### CODE REVIEW

**Comment by trygve-lie** [comment]
Should aliasing be a sub argument of each? Like: `eik package alias`

**Comment by digitalsadhu** [comment]
The advantage in my mind is that you can see all the commands from the help without having to dig deeper. I used to have it `eik alias <type>` eg. `eik alias map` but its not as clear without digging deeper. What I really wanted was that we would only need `eik alias` and the cmd could figure out which type but alas, dont think thats possible

**Comment by digitalsadhu** [comment]
`eik package alias` looks decent though 🤷

**Comment by digitalsadhu** [comment]
Eg. You can see all the commands and what they do immediately without needing to dig into the package command:

Screenshot 2020-05-05 at 23 12 18

**Comment by digitalsadhu** [comment]
I'm going to merge as is for now. Happy to continue discussion and potentially refactor these commands again

**Pull request merged**
