### PR TITLE
feat: replace 'js' and 'css' eik.json keys with 'entrypoints'

### PR DESCRIPTION
**Pull request by digitalsadhu**
This PR replaces the use of `js` and `css` keys in `eik.json` with `entrypoints` which can be used to map `js`, `css` or other client side assets such as `svg` etc.

```json
{
    "name": "my-app",
    "version": "1.0.0",
    "server": "https://assets.finn.no",
    "entrypoints": {
        "./esm.js": "eik/esm.js",
        "./esm.js.map": "eik/esm.js.map",
        "./ie11.js": "eik/ie11.js",
        "./ie11.js.map": "eik/ie11.js.map",
        "./index.css": "src/client/index.css",
        "./icons/thing.svg": "./src/client/icons/thing.svg"
    },
    "import-map": "https://assets.finn.no/map/finn/v2"
}

```

### CODE REVIEW

**Comment by digitalsadhu** [comment]
@stipsan I can see that for sure. I think we went with the way we did in an attempt to be similar to package entrypoints in node: https://nodejs.org/api/esm.html#esm_package_entry_points

**Comment by trygve-lie** [comment]
I am not sure I follow why there is an input and output. Won't we just be able to say "here is multiple files / paths, duplicates not allowed, we want to pack up into the tar and upload"?

**Comment by digitalsadhu** [comment]
Last discussion we had we decided to try to line things up with the node entrypoints stuff https://nodejs.org/api/esm.html#esm_package_entry_points

We can of course just drop that and use an array?

I think having the mappings is good since you can control how things are placed on the server. Handy if you want to scope something like SVG icons under /icons or something.

**Comment by stipsan** [comment]
I agree, I think as a consumer I'd prefer to just give it a folder and just have everything in that folder be mirrored on the cdn.

**Comment by digitalsadhu** [comment]
Just giving it a folder means you have to massage things yourself which probably isn't ideal. Take displayads podlet where the CSS is not in the same place as the JS build output. You'd have to add your own copy step. I'd rather a string or array of string values where the string could be a path to a file or directory but you could give it an array with several paths.

**Comment by trygve-lie** [comment]
What about the following:

```js
{
    entrypoints: {
        [dir / filepath on cdn]: [input glob]
    }
}
```

The keys in the entry point object is where the files will be on the CDN. By having it so its not possible to add duplicate destination folders / files on the CDN which can cause files overwriting each other.

Then the property of the key is a [glob](https://github.com/isaacs/node-glob),

Example:

```js
{
    entrypoints: { 
        "/js/app.js": "./assets/javascript/file.js",
        "/css": "./assets/styles/*.css",
        "/gfx: "./images/**./*.svg"
    }
}
```

**Comment by trygve-lie** [comment]
> I agree, I think as a consumer I'd prefer to just give it a folder and just have everything in that folder be mirrored on the cdn.

If one want to mirror a folder you just do like this:

```js
{
    entrypoints: { 
        "/": "./assets"
    }
}
```

**Comment by digitalsadhu** [comment]
The following syntaxes are now supported...

```json
{
  "/": "./assets/*",
  "/icons": "./icons/**/*.svg",
  "/index.js": "./assets/index.js"
}
```

**Pull request merged**
